In [ ]:
# AI-Powered Patient Readmission Risk & Healthcare Resource Intelligence System

## Step 1: Dataset Understanding

This notebook explores the Diabetes 130-US Hospitals for Years 1999–2008 dataset.

### Objective
To understand the dataset structure, features, missing values, duplicates, target variable, and patient-level records before preprocessing and machine learning.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../UCI-dataset/diabetic_data.csv")

In [3]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [4]:
print("Dataset Shape:", df.shape)

Dataset Shape: (101766, 50)

In [5]:
print(df.columns.tolist())

['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'payer_code', 'medical_specialty', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    101766 non-null  str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  str
 11  medical_specialty         101766 non-null  str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  str
 19  diag_2                    101766 non-null  str
 20  diag_3                    101766 non-null  str
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
dtypes: int64(13), str(37)
memory usage: 38.8 MB

In [7]:
# Standard missing values
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [8]:
# Missing values represented as '?'
(df == "?").sum()

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [9]:
missing_question_marks = (df == "?").sum()

missing_question_marks[missing_question_marks > 0].sort_values(ascending=False)

weight               98569
medical_specialty    49949
payer_code           40256
race                  2273
diag_3                1423
diag_2                 358
diag_1                  21
dtype: int64

In [10]:
import numpy as np

df = df.replace("?", np.nan)

df.isnull().sum().sort_values(ascending=False)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
encounter_id                    0
admission_type_id               0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
num_medications                 0
num_procedures                  0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage[missing_percentage > 0].sort_values(ascending=False)

weight               96.858479
max_glu_serum        94.746772
A1Cresult            83.277322
medical_specialty    49.082208
payer_code           39.557416
race                  2.233555
diag_3                1.398306
diag_2                0.351787
diag_1                0.020636
dtype: float64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["readmitted"].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [14]:
df["readmitted_30"] = (df["readmitted"] == "<30").astype(int)

In [15]:
df["readmitted_30"].value_counts()

readmitted_30
0    90409
1    11357
Name: count, dtype: int64

In [16]:
df["readmitted_30"].value_counts(normalize=True) * 100

readmitted_30
0    88.840084
1    11.159916
Name: proportion, dtype: float64

In [17]:
df["patient_nbr"].nunique()

71518

In [18]:
df["patient_nbr"].value_counts().head()

patient_nbr
88785891    40
43140906    28
1660293     23
23199021    23
88227540    23
Name: count, dtype: int64

In [19]:
selected_features = [
    "age",
    "gender",
    "admission_type_id",
    "admission_source_id",
    "time_in_hospital",
    "num_lab_procedures",
    "num_procedures",
    "num_medications",
    "number_outpatient",
    "number_emergency",
    "number_inpatient",
    "number_diagnoses",
    "insulin",
    "change",
    "diabetesMed"
]

X = df[selected_features]
y = df["readmitted_30"]

X.shape, y.shape

((101766, 15), (101766,))

In [20]:
X.head()

,age,gender,admission_type_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,insulin,change,diabetesMed
0,[0-10),Female,6,1,1,41,0,1,0,0,0,1,No,No,No
1,[10-20),Female,1,7,3,59,0,18,0,0,0,9,Up,Ch,Yes
2,[20-30),Female,1,7,2,11,5,13,2,0,1,6,No,No,Yes
3,[30-40),Male,1,7,2,44,1,16,0,0,0,7,Up,Ch,Yes
4,[40-50),Male,1,7,1,51,0,8,0,0,0,5,Steady,Ch,Yes

In [22]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   age                  101766 non-null  str
 1   gender               101766 non-null  str
 2   admission_type_id    101766 non-null  int64
 3   admission_source_id  101766 non-null  int64
 4   time_in_hospital     101766 non-null  int64
 5   num_lab_procedures   101766 non-null  int64
 6   num_procedures       101766 non-null  int64
 7   num_medications      101766 non-null  int64
 8   number_outpatient    101766 non-null  int64
 9   number_emergency     101766 non-null  int64
 10  number_inpatient     101766 non-null  int64
 11  number_diagnoses     101766 non-null  int64
 12  insulin              101766 non-null  str
 13  change               101766 non-null  str
 14  diabetesMed          101766 non-null  str
dtypes: int64(10), str(5)
memory usage: 11.6 MB

In [26]:
%pip install scikit-learn

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\HC\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\narwhals\\_arrow\\series_struct.py'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\HC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl (8.4 MB)
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.4 MB 165.9 kB/s eta 0:00:48
   -- ------------------------------------- 0.5/8.4 MB 165.9 kB/s eta 0:00:48
   -- ------------------------------------- 0.5/8.4 MB 165.9 kB/s eta 0:00:48
   -- ------------------------------------- 0.5/8.4 MB 165.9 kB/s eta 0:00:48
   -- ------------------------------------- 0.5/8.4 MB 165.9 kB/s eta 0:00:48
   --- ------------------------------------ 0.8/8.4 MB 198.6 kB/s eta 0:00:39
   --- ------------------------------------ 0.8/8.4 MB 198.6 kB/s eta 0:00:39
   --- ------------------------------------ 0.8/8.4 MB 198.6 kB/s eta 0:00:39
   ----- ---------------------------------- 1.0/8.4 MB 243.3 kB/s eta 0:00:31
   ----- ---------------------------------- 1.0/8.4 MB 243.3 kB/s eta 0:00:31
   ----- ---------------------------------- 1.0/8.4 MB 243.3 kB/s eta 0:00:31
   ----- ---------------------------------- 1.0/8.4 MB 243.3 kB/s eta 0:00:31
   ----- ---------------------------------- 1.0/8.4 MB 243.3 kB/s eta 0:00:31
   ------ --------------------------------- 1.3/8.4 MB 244.0 kB/s eta 0:00:29
   ------ --------------------------------- 1.3/8.4 MB 244.0 kB/s eta 0:00:29
   ------- -------------------------------- 1.6/8.4 MB 272.7 kB/s eta 0:00:25
   -------- ------------------------------- 1.8/8.4 MB 312.7 kB/s eta 0:00:21
   ---------- ----------------------------- 2.1/8.4 MB 344.1 kB/s eta 0:00:19
   ---------- ----------------------------- 2.1/8.4 MB 344.1 kB/s eta 0:00:19
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ----------- ---------------------------- 2.4/8.4 MB 358.3 kB/s eta 0:00:17
   ------------ --------------------------- 2.6/8.4 MB 254.0 kB/s eta 0:00:23
   ------------ --------------------------- 2.6/8.4 MB 254.0 kB/s eta 0:00:23
   ------------- -------------------------- 2.9/8.4 MB 268.9 kB/s eta 0:00:21
   --------------- ------------------------ 3.1/8.4 MB 289.0 kB/s eta 0:00:19
   --------------- ------------------------ 3.1/8.4 MB 289.0 kB/s eta 0:00:19
   ----------------- ---------------------- 3.7/8.4 MB 327.1 kB/s eta 0:00:15
   ----------------- ---------------------- 3.7/8.4 MB 327.1 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.4 MB 356.1 kB/s eta 0:00:12
   -------------------- ------------------- 4.2/8.4 MB 356.1 kB/s eta 0:00:12
   ---------------------- ----------------- 4.7/8.4 MB 388.3 kB/s eta 0:00:10
   ---------------------- ----------------- 4.7/8.4 MB 388.3 kB/s eta 0:00:10
   ----------------------- ---------------- 5.0/8.4 MB 384.8 kB/s eta 0:00:09
   ----------------------- ---------------- 5.0/8.4 MB 384.8 kB/s eta 0:00:09
   ------------------------- -------------- 5.2/8.4 MB 390.5 kB/s eta 0:00:09
   ------------------------- -------------- 5.2/8.4 MB 390.5 kB/s eta 0:00:09
   -------------------------- ------------- 5.5/8.4 MB 395.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.4 MB 395.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.4 MB 395.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.4 MB 395.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.4 MB 395.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.4 MB 395.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.4 MB 395.5 kB/s eta 0:00:08
   --------------------------- ------------ 5.8/8.4 MB 366.2 kB/s eta 0:00:08
   --------------------------- ------------ 5.8/8.4 MB 366.2 kB/s eta 0:00:08
   --------------------------- ------------ 5.8/8.4 MB 366.2 kB/s eta 0:00:08
   --------------------------- ------------ 5.8/8.4 MB 366.2 kB/s eta 0:00:08
   ---------------------------- ----------- 6.0/8.4 MB 361.9 kB/s eta 0:00:07
   ---------------------------- ----------- 6.0/8.4 MB 361.9 kB/s eta 0:00:07
   ---------------------------- ----------- 6.0/8.4 MB 361.9 kB/s eta 0:00:07
   ---------------------------- ----------- 6.0/8.4 MB 361.9 kB/s eta 0:00:07
   ------------------------------ --------- 6.3/8.4 MB 353.7 kB/s eta 0:00:06
   ------------------------------ --------- 6.3/8.4 MB 353.7 kB/s eta 0:00:06
   ------------------------------ --------- 6.3/8.4 MB 353.7 kB/s eta 0:00:06
   ------------------------------ --------- 6.3/8.4 MB 353.7 kB/s eta 0:00:06
   ------------------------------- -------- 6.6/8.4 MB 353.2 kB/s eta 0:00:06
   ------------------------------- -------- 6.6/8.4 MB 353.2 kB/s eta 0:00:06
   ------------------------------- -------- 6.6/8.4 MB 353.2 kB/s eta 0:00:06
   -------------------------------- ------- 6.8/8.4 MB 355.5 kB/s eta 0:00:05
   -------------------------------- ------- 6.8/8.4 MB 355.5 kB/s eta 0:00:05
   -------------------------------- ------- 6.8/8.4 MB 355.5 kB/s eta 0:00:05
   --------------------------------- ------ 7.1/8.4 MB 357.4 kB/s eta 0:00:04
   --------------------------------- ------ 7.1/8.4 MB 357.4 kB/s eta 0:00:04
   --------------------------------- ------ 7.1/8.4 MB 357.4 kB/s eta 0:00:04
   ----------------------------------- ---- 7.3/8.4 MB 358.5 kB/s eta 0:00:03
   ----------------------------------- ---- 7.3/8.4 MB 358.5 kB/s eta 0:00:03
   ----------------------------------- ---- 7.3/8.4 MB 358.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.6/8.4 MB 358.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.6/8.4 MB 358.5 kB/s eta 0:00:03
   ------------------------------------- -- 7.9/8.4 MB 363.9 kB/s eta 0:00:02
   ------------------------------------- -- 7.9/8.4 MB 363.9 kB/s eta 0:00:02
   ------------------------------------- -- 7.9/8.4 MB 363.9 kB/s eta 0:00:02
   -------------------------------------- - 8.1/8.4 MB 363.7 kB/s eta 0:00:01
   -------------------------------------- - 8.1/8.4 MB 363.7 kB/s eta 0:00:01
   -------------------------------------- - 8.1/8.4 MB 363.7 kB/s eta 0:00:01
   ---------------------------------------- 8.4/8.4 MB 364.7 kB/s  0:00:25
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl (37.4 MB)
   ---------------------------------------- 0.0/37.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.4 MB ? eta -:--:--
    --------------------------------------- 0.5/37.4 MB 940.2 kB/s eta 0:00:40
    --------------------------------------- 0.5/37.4 MB 940.2 kB/s eta 0:00:40
    --------------------------------------- 0.8/37.4 MB 913.9 kB/s eta 0:00:41
   - -------------------------------------- 1.0/37.4 MB 848.5 kB/s eta 0:00:43
   - -------------------------------------- 1.3/37.4 MB 930.5 kB/s eta 0:00:39
   - -------------------------------------- 1.6/37.4 MB 996.1 kB/s eta 0:00:36
   - -------------------------------------- 1.8/37.4 MB 938.8 kB/s eta 0:00:38
   -- ------------------------------------- 2.1/37.4 MB 1.1 MB/s eta 0:00:34
   -- ------------------------------------- 2.6/37.4 MB 1.1 MB/s eta 0:00:33
   -- ------------------------------------- 2.6/37.4 MB 1.1 MB/s eta 0:00:33
   --- ------------------------------------ 3.1/37.4 MB 1.1 MB/s eta 0:00:30
   --- ------------------------------------ 3.1/37.4 MB 1.1 MB/s eta 0:00:30
   --- ------------------------------------ 3.4/37.4 MB 1.1 MB/s eta 0:00:31
   --- ------------------------------------ 3.4/37.4 MB 1.1 MB/s eta 0:00:31
   --- ------------------------------------ 3.7/37.4 MB 1.0 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/37.4 MB 1.0 MB/s eta 0:00:33
   ---- ----------------------------------- 3.9/37.4 MB 929.0 kB/s eta 0:00:36
   ---- ----------------------------------- 3.9/37.4 MB 929.0 kB/s eta 0:00:36
   ---- ----------------------------------- 3.9/37.4 MB 929.0 kB/s eta 0:00:36
   ---- ----------------------------------- 3.9/37.4 MB 929.0 kB/s eta 0:00:36
   ---- ----------------------------------- 3.9/37.4 MB 929.0 kB/s eta 0:00:36
   ---- ----------------------------------- 3.9/37.4 MB 929.0 kB/s eta 0:00:36
   ---- ----------------------------------- 4.2/37.4 MB 759.2 kB/s eta 0:00:44
   ---- ----------------------------------- 4.2/37.4 MB 759.2 kB/s eta 0:00:44
   ---- ----------------------------------- 4.2/37.4 MB 759.2 kB/s eta 0:00:44
   ---- ----------------------------------- 4.5/37.4 MB 716.0 kB/s eta 0:00:46
   ---- ----------------------------------- 4.5/37.4 MB 716.0 kB/s eta 0:00:46
   ----- ---------------------------------- 4.7/37.4 MB 714.5 kB/s eta 0:00:46
   ----- ---------------------------------- 4.7/37.4 MB 714.5 kB/s eta 0:00:46
   ----- ---------------------------------- 5.2/37.4 MB 735.0 kB/s eta 0:00:44
   ----- ---------------------------------- 5.2/37.4 MB 735.0 kB/s eta 0:00:44
   ----- ---------------------------------- 5.5/37.4 MB 737.4 kB/s eta 0:00:44
   ------ --------------------------------- 5.8/37.4 MB 740.5 kB/s eta 0:00:43
   ------ --------------------------------- 5.8/37.4 MB 740.5 kB/s eta 0:00:43
   ------ --------------------------------- 6.0/37.4 MB 743.5 kB/s eta 0:00:43
   ------ --------------------------------- 6.0/37.4 MB 743.5 kB/s eta 0:00:43
   ------ --------------------------------- 6.3/37.4 MB 736.8 kB/s eta 0:00:43
   ------ --------------------------------- 6.3/37.4 MB 736.8 kB/s eta 0:00:43
   ------- -------------------------------- 6.6/37.4 MB 733.4 kB/s eta 0:00:43
   ------- -------------------------------- 6.6/37.4 MB 733.4 kB/s eta 0:00:43
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/37.4 MB 728.4 kB/s eta 0:00:42
   -------- ------------------------------- 8.4/37.4 MB 718.1 kB/s eta 0:00:41
   -------- ------------------------------- 8.4/37.4 MB 718.1 kB/s eta 0:00:41
   ---------- ----------------------------- 9.4/37.4 MB 781.7 kB/s eta 0:00:36
   ---------- ----------------------------- 9.4/37.4 MB 781.7 kB/s eta 0:00:36
   ---------- ----------------------------- 10.0/37.4 MB 798.2 kB/s eta 0:00:35
   ----------- ---------------------------- 10.7/37.4 MB 843.6 kB/s eta 0:00:32
   ------------ --------------------------- 11.5/37.4 MB 891.1 kB/s eta 0:00:29
   ------------- -------------------------- 12.3/37.4 MB 934.4 kB/s eta 0:00:27
   -------------- ------------------------- 13.6/37.4 MB 1.0 MB/s eta 0:00:24
   -------------- ------------------------- 13.9/37.4 MB 1.0 MB/s eta 0:00:24
   --------------- ------------------------ 14.2/37.4 MB 1.0 MB/s eta 0:00:23
   --------------- ------------------------ 14.7/37.4 MB 1.0 MB/s eta 0:00:22
   --------------- ------------------------ 14.9/37.4 MB 1.0 MB/s eta 0:00:22
   --------------- ------------------------ 14.9/37.4 MB 1.0 MB/s eta 0:00:22
   --------------- ------------------------ 14.9/37.4 MB 1.0 MB/s eta 0:00:22
   --------------- ------------------------ 14.9/37.4 MB 1.0 MB/s eta 0:00:22
   ---------------- ----------------------- 15.2/37.4 MB 999.1 kB/s eta 0:00:23
   ---------------- ----------------------- 15.2/37.4 MB 999.1 kB/s eta 0:00:23
   ---------------- ----------------------- 15.7/37.4 MB 994.3 kB/s eta 0:00:22
   ----------------- ---------------------- 16.3/37.4 MB 1.0 MB/s eta 0:00:21
   ----------------- ---------------------- 16.5/37.4 MB 1.0 MB/s eta 0:00:21
   ------------------ --------------------- 17.0/37.4 MB 1.0 MB/s eta 0:00:20
   ------------------ --------------------- 17.6/37.4 MB 1.0 MB/s eta 0:00:19
   ------------------- -------------------- 18.4/37.4 MB 1.1 MB/s eta 0:00:18
   -------------------- ------------------- 18.9/37.4 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 18.9/37.4 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 18.9/37.4 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.1/37.4 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.4/37.4 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.4/37.4 MB 1.1 MB/s eta 0:00:17
   -------------------- ------------------- 19.4/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.4 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.9/37.4 MB 952.4 kB/s eta 0:00:19
   --------------------- ------------------ 20.2/37.4 MB 950.5 kB/s eta 0:00:19
   --------------------- ------------------ 20.2/37.4 MB 950.5 kB/s eta 0:00:19
   --------------------- ------------------ 20.2/37.4 MB 950.5 kB/s eta 0:00:19
   --------------------- ------------------ 20.2/37.4 MB 950.5 kB/s eta 0:00:19
   --------------------- ------------------ 20.2/37.4 MB 950.5 kB/s eta 0:00:19
   --------------------- ------------------ 20.2/37.4 MB 950.5 kB/s eta 0:00:19
   --------------------- ------------------ 20.2/37.4 MB 950.5 kB/s eta 0:00:19
   --------------------- ------------------ 20.4/37.4 MB 894.6 kB/s eta 0:00:19
   --------------------- ------------------ 20.4/37.4 MB 894.6 kB/s eta 0:00:19
   --------------------- ------------------ 20.4/37.4 MB 894.6 kB/s eta 0:00:19
   ---------------------- ----------------- 20.7/37.4 MB 882.3 kB/s eta 0:00:19
   ---------------------- ----------------- 21.2/37.4 MB 888.2 kB/s eta 0:00:19
   ----------------------- ---------------- 21.5/37.4 MB 893.6 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 21.8/37.4 MB 895.7 kB/s eta 0:00:18
   ----------------------- ---------------- 22.0/37.4 MB 800.9 kB/s eta 0:00:20
   ----------------------- ---------------- 22.0/37.4 MB 800.9 kB/s eta 0:00:20
   ----------------------- ---------------- 22.0/37.4 MB 800.9 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20
   ----------------------- ---------------- 22.3/37.4 MB 785.4 kB/s eta 0:00:20

Collecting scikit-learn
  Using cached scikit_learn-1.9.1-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\HC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\HC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.1)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\HC\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Using cached scikit_learn-1.9.1-cp314-cp314-win_amd64.whl (8.4 MB)
Using cached joblib-1.6.0-py3-none-any.whl (306 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached narwhals-2.26.0-py3-none-any.whl (474 kB)
Installing collected packages: narwhals, cloudpickle, joblib, scikit-learn

   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]
   ---------------------------------------- 0/4 [narwhals]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
from sklearn.model_selection import GroupShuffleSplit

print("Scikit-learn is ready!")

Scikit-learn is ready!